# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class Test004():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_004(self):
    self.driver.get("https://bbs.nansin.top/")
    self.driver.set_window_size(1294, 766)
    login_btn = WebDriverWait(self.driver, 10).until(
        EC.element_to_be_clickable((By.CSS_SELECTOR, ".ant-btn:nth-child(1)"))
    )
    login_btn.click()

    # 悬停操作
    actions = ActionChains(self.driver)
    actions.move_to_element(login_btn).perform()

    # 输入用户名和密码
    self.driver.find_element(By.ID, "normal_login_name").send_keys("kiwitest1")
    self.driver.find_element(By.ID, "normal_login_password").send_keys("kiwi4567")

    # 点击登录按钮
    self.driver.find_element(By.CSS_SELECTOR, ".login-form-button").click()

    # 等待头像加载（注意：等待时间应为秒）
    WebDriverWait(self.driver, 30).until(
        EC.presence_of_element_located((By.XPATH, "//img[@alt='kiwitest1']"))
    )

    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//img[@alt=\'kiwitest1\']")))

    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//img[@alt=\'kiwitest1\']")))
    self.driver.find_element(By.CSS_SELECTOR, ".avatar > img").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".profile").click()
    time.sleep(1)
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".follow-btn")))
    self.driver.find_element(By.CSS_SELECTOR, ".follow-btn").click()
    WebDriverWait(self.driver, 10).until(
    EC.element_to_be_clickable((By.CSS_SELECTOR, ".ant-row:nth-child(4) .ant-input"))
).click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-row:nth-child(4) .ant-input").send_keys("测试工程师")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-row:nth-child(5) .ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".ant-row:nth-child(5) .ant-input").send_keys("南生测试公司")
    self.driver.find_element(By.CSS_SELECTOR, ".homePage > .ant-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".homePage > .ant-input").send_keys("https://personal.com.cn")
    self.driver.find_element(By.CSS_SELECTOR, ".intro").click()
    self.driver.find_element(By.CSS_SELECTOR, ".intro").send_keys("喜欢看电影")
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".ant-row:nth-child(6) .ant-form-explain")
    assert len(elements) == 0
  
