# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test001():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_001(self):
    self.driver.get("https://bbs.nansin.top//")
    self.driver.set_window_size(1294, 766)
    WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR, ".ant-btn")))
    self.driver.find_element(By.CSS_SELECTOR, ".ant-btn").click()
    self.driver.find_element(By.ID, "normal_login_name").click()
    self.driver.find_element(By.ID, "normal_login_name").send_keys("kiwitest")
    self.driver.find_element(By.ID, "normal_login_password").click()
    self.driver.find_element(By.ID, "normal_login_password").send_keys("kiwi1456")
    self.driver.find_element(By.CSS_SELECTOR, ".login-form-button").click()
    WebDriverWait(self.driver, 3000).until(expected_conditions.invisibility_of_element_located((By.XPATH, "//img[@alt=\'kiwitest1\']")))
    elements = self.driver.find_elements(By.XPATH, "//img[@alt=\'kiwitest1\']")
    assert len(elements) == 0
  
